apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: feed-content-service
  labels:
    app: action-feed
    service: feed-content-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
    - http:
        paths:
          - path: /api/feed-content
            backend:
              serviceName: feed-content-service
              servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: feed-content-service
spec:
  selector:
    app: action-feed
    service: feed-content-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-content-service
  labels:
    app: action-feed
    service: feed-content-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "sidecar.istio.io/inject": "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: action-feed
      service: feed-content-service
  template:
    metadata:
      labels:
        app: action-feed
        service: feed-content-service
    spec:
      volumes:
        - name: bootstrap
          secret:
            secretName: bootstrap-yaml
      containers:
        - name: feed-content-service
          image: "feed-content-service:{{ .Values.services.feedContentService.buildId }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: config
              name: bootstrap
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /actuator/health
              port: http
          livenessProbe:
            initialDelaySeconds: 100
            httpGet:
              path: /actuator/health
              port: http
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: feed-content-service
  labels:
    app: action-feed
    service: feed-content-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  application-k8s.yaml: |-
    af:
        search:
            client:
                uri: http://feed-search-service/api/feed-search
        auth:
            jwt-secret: ${AUTH_JWT_PASSWORD}
        data:
            r2dbc:
                host: action-feed-postgresql
                password: secret
