apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ui-service
  labels:
    app: action-feed
    service: ui-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: ui-service
              servicePort: http
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
spec:
  selector:
    app: action-feed
    service: ui-service
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-service
  labels:
    app: action-feed
    service: ui-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "sidecar.istio.io/inject": "true"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: action-feed
      service: ui-service
  template:
    metadata:
      labels:
        app: action-feed
        service: ui-service
    spec:
      containers:
        - name: ui-service
          image: "ui-service:{{ .Values.services.uiService.buildId }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
          livenessProbe:
            httpGet:
              path: /
              port: http
